export type CuratedMediaType = "image" | "video";

export type CuratedMediaItem = {
  id: string;
  type: CuratedMediaType;
  src: string;
  poster?: string;
  brand: string;
  brandLabel: string;
  project: string;
  projectLabel: string;
  title: string;
  relatedSlugs: string[];
  featuredArea: string[];
};

const CURATED_MEDIA_ITEMS: CuratedMediaItem[] = [
  {
    id: "defender-black-110-01",
    type: "image",
    src: "/media/fdl/defender/black-110-01.jpg",
    brand: "defender",
    brandLabel: "Defender",
    project: "black-110-bodykit",
    projectLabel: "Black 110 Bodykit",
    title: "Defender 110 bodykit build",
    relatedSlugs: ["land-rover-defender", "defender-l663"],
    featuredArea: ["home-hero", "home-expertise", "services", "defender", "gallery", "shop-category"],
  },
  {
    id: "defender-black-110-02",
    type: "image",
    src: "/media/fdl/defender/black-110-02.jpg",
    brand: "defender",
    brandLabel: "Defender",
    project: "black-110-bodykit",
    projectLabel: "Black 110 Bodykit",
    title: "Defender 110 side profile",
    relatedSlugs: ["land-rover-defender", "defender-l663"],
    featuredArea: ["defender", "gallery", "shop-category"],
  },
  {
    id: "defender-v8-black-01",
    type: "image",
    src: "/media/fdl/defender/v8-black-01.jpg",
    brand: "defender",
    brandLabel: "Defender",
    project: "defender-v8-black",
    projectLabel: "Defender V8 Black",
    title: "Defender V8 detail shot",
    relatedSlugs: ["land-rover-defender", "defender-l663"],
    featuredArea: ["services", "defender", "gallery", "shop-category"],
  },
  {
    id: "defender-v8-black-02",
    type: "image",
    src: "/media/fdl/defender/v8-black-02.jpg",
    brand: "defender",
    brandLabel: "Defender",
    project: "defender-v8-black",
    projectLabel: "Defender V8 Black",
    title: "Defender V8 workshop angle",
    relatedSlugs: ["land-rover-defender", "defender-l663"],
    featuredArea: ["services", "gallery", "shop-category"],
  },
  {
    id: "defender-lm-satin-01",
    type: "image",
    src: "/media/fdl/defender/lm-satin-01.jpg",
    brand: "defender",
    brandLabel: "Defender",
    project: "lm-bodykit-satin-black",
    projectLabel: "LM Bodykit Satin Black",
    title: "Defender LM bodykit rear view",
    relatedSlugs: ["land-rover-defender", "defender-l663"],
    featuredArea: ["services", "defender", "gallery", "shop-category"],
  },
  {
    id: "defender-lm-satin-02",
    type: "image",
    src: "/media/fdl/defender/lm-satin-02.jpg",
    brand: "defender",
    brandLabel: "Defender",
    project: "lm-bodykit-satin-black",
    projectLabel: "LM Bodykit Satin Black",
    title: "Defender LM bodykit detail",
    relatedSlugs: ["land-rover-defender", "defender-l663"],
    featuredArea: ["defender", "gallery", "shop-category"],
  },
  {
    id: "defender-borasco-grey-01",
    type: "image",
    src: "/media/fdl/defender/borasco-grey-01.jpg",
    brand: "defender",
    brandLabel: "Defender",
    project: "borasco-grey",
    projectLabel: "Borasco Grey",
    title: "Borasco grey Defender build",
    relatedSlugs: ["land-rover-defender", "defender-l663"],
    featuredArea: ["defender", "gallery", "shop-category"],
  },
  {
    id: "bmw-x5-lci-01",
    type: "image",
    src: "/media/fdl/bmw/x5-lci-01.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x5-lci",
    projectLabel: "BMW X5 LCI",
    title: "BMW X5 LCI front three-quarter",
    relatedSlugs: ["x5-g05-lci"],
    featuredArea: ["home-hero", "services", "gallery", "shop-category"],
  },
  {
    id: "bmw-x5-lci-02",
    type: "image",
    src: "/media/fdl/bmw/x5-lci-02.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x5-lci",
    projectLabel: "BMW X5 LCI",
    title: "BMW X5 LCI workshop profile",
    relatedSlugs: ["x5-g05-lci"],
    featuredArea: ["services", "gallery", "shop-category"],
  },
  {
    id: "bmw-x5-lci-03",
    type: "image",
    src: "/media/fdl/bmw/x5-lci-03.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x5-lci",
    projectLabel: "BMW X5 LCI",
    title: "BMW X5 LCI side angle",
    relatedSlugs: ["x5-g05-lci"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "bmw-x5-g05-facelift-blue-01",
    type: "image",
    src: "/media/fdl/bmw/x5-g05-facelift-blue-01.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x5-g05-facelift",
    projectLabel: "BMW X5 G05 Facelift",
    title: "BMW X5 G05 facelift front view",
    relatedSlugs: ["x5-g05"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "bmw-x5-g05-facelift-white-01",
    type: "image",
    src: "/media/fdl/bmw/x5-g05-facelift-white-01.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x5-g05-facelift",
    projectLabel: "BMW X5 G05 Facelift",
    title: "BMW X5 G05 facelift white build",
    relatedSlugs: ["x5-g05"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "bmw-x5m-carbon-01",
    type: "image",
    src: "/media/fdl/bmw/x5m-carbon-01.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x5m-carbon-edition",
    projectLabel: "BMW X5M Carbon Edition",
    title: "BMW X5M carbon edition detail",
    relatedSlugs: ["x5m", "x5m-lci"],
    featuredArea: ["services", "gallery", "shop-category"],
  },
  {
    id: "bmw-x5m-carbon-02",
    type: "image",
    src: "/media/fdl/bmw/x5m-carbon-02.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x5m-carbon-edition",
    projectLabel: "BMW X5M Carbon Edition",
    title: "BMW X5M carbon edition exterior",
    relatedSlugs: ["x5m", "x5m-lci"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "bmw-420d-f32-zayn-01",
    type: "image",
    src: "/media/fdl/bmw/420d-f32-zayn-01.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "420d-f32-zayn",
    projectLabel: "BMW 420D F32 Zayn",
    title: "BMW 420D F32 Zayn still",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "bmw-m3-f80-01",
    type: "image",
    src: "/media/fdl/bmw/m3-f80-01.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "m3-f80",
    projectLabel: "BMW M3 F80",
    title: "BMW M3 F80 satin black still",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "audi-r8-01",
    type: "image",
    src: "/media/fdl/audi/r8-01.jpg",
    brand: "audi",
    brandLabel: "Audi",
    project: "audi-r8",
    projectLabel: "Audi R8",
    title: "Audi R8 side profile",
    relatedSlugs: ["audi-r8"],
    featuredArea: ["services", "gallery", "shop-category"],
  },
  {
    id: "audi-r8-02",
    type: "image",
    src: "/media/fdl/audi/r8-02.jpg",
    brand: "audi",
    brandLabel: "Audi",
    project: "audi-r8",
    projectLabel: "Audi R8",
    title: "Audi R8 carbon detail",
    relatedSlugs: ["audi-r8"],
    featuredArea: ["services", "gallery", "shop-category"],
  },
  {
    id: "audi-r8-03",
    type: "image",
    src: "/media/fdl/audi/r8-03.jpg",
    brand: "audi",
    brandLabel: "Audi",
    project: "audi-r8",
    projectLabel: "Audi R8",
    title: "Audi R8 rear view",
    relatedSlugs: ["audi-r8"],
    featuredArea: ["home-hero", "gallery", "shop-category"],
  },
  {
    id: "range-rover-sport-lm-01",
    type: "image",
    src: "/media/fdl/range-rover/sport-lm-01.jpg",
    brand: "range-rover",
    brandLabel: "Range Rover",
    project: "sport-lm-bodykit",
    projectLabel: "Range Rover Sport LM Bodykit",
    title: "Range Rover Sport bodykit build",
    relatedSlugs: ["range-rover-sport", "l494-sport", "l461-sport"],
    featuredArea: ["home-hero", "services", "gallery", "shop-category"],
  },
  {
    id: "range-rover-sport-satin-01",
    type: "image",
    src: "/media/fdl/range-rover/sport-satin-01.jpg",
    brand: "range-rover",
    brandLabel: "Range Rover",
    project: "sport-lm-satin-black",
    projectLabel: "Range Rover Sport Satin Black",
    title: "Range Rover Sport satin black front view",
    relatedSlugs: ["range-rover-sport", "l494-sport", "l461-sport"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "range-rover-sport-satin-02",
    type: "image",
    src: "/media/fdl/range-rover/sport-satin-02.jpg",
    brand: "range-rover",
    brandLabel: "Range Rover",
    project: "sport-lm-satin-black",
    projectLabel: "Range Rover Sport Satin Black",
    title: "Range Rover Sport satin black side profile",
    relatedSlugs: ["range-rover-sport", "l494-sport", "l461-sport"],
    featuredArea: ["services", "gallery", "shop-category"],
  },
  {
    id: "range-rover-svr-01",
    type: "image",
    src: "/media/fdl/range-rover/svr-01.jpg",
    brand: "range-rover",
    brandLabel: "Range Rover",
    project: "range-rover-svr",
    projectLabel: "Range Rover SVR",
    title: "Range Rover SVR detail shot",
    relatedSlugs: ["range-rover-sport", "l494-sport", "l461-sport", "l405-vogue", "l460-vogue"],
    featuredArea: ["services", "gallery", "shop-category"],
  },
  {
    id: "porsche-taycan-01",
    type: "image",
    src: "/media/fdl/porsche/taycan-01.jpg",
    brand: "porsche",
    brandLabel: "Porsche",
    project: "taycan-wrap-wheels",
    projectLabel: "Porsche Taycan Wrap + Wheels",
    title: "Porsche Taycan wrap build",
    relatedSlugs: ["taycan"],
    featuredArea: ["services", "gallery", "shop-category"],
  },
  {
    id: "porsche-taycan-02",
    type: "image",
    src: "/media/fdl/porsche/taycan-02.jpg",
    brand: "porsche",
    brandLabel: "Porsche",
    project: "taycan-wrap-wheels",
    projectLabel: "Porsche Taycan Wrap + Wheels",
    title: "Porsche Taycan side angle",
    relatedSlugs: ["taycan"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "mercedes-gle-01",
    type: "image",
    src: "/media/fdl/mercedes/gle-01.jpg",
    brand: "mercedes",
    brandLabel: "Mercedes",
    project: "gle-blackout-bodykit",
    projectLabel: "Mercedes GLE Blackout + Bodykit",
    title: "Mercedes GLE blackout front view",
    relatedSlugs: ["gle"],
    featuredArea: ["services", "gallery", "shop-category"],
  },
  {
    id: "mercedes-gle-02",
    type: "image",
    src: "/media/fdl/mercedes/gle-02.jpg",
    brand: "mercedes",
    brandLabel: "Mercedes",
    project: "gle-blackout-bodykit",
    projectLabel: "Mercedes GLE Blackout + Bodykit",
    title: "Mercedes GLE moody workshop angle",
    relatedSlugs: ["gle"],
    featuredArea: ["services", "gallery", "shop-category"],
  },
  {
    id: "branding-amarok-01",
    type: "image",
    src: "/media/fdl/branding/amarok-01.jpg",
    brand: "branding",
    brandLabel: "Branding",
    project: "amarok-europa",
    projectLabel: "Amarok Europa Branding",
    title: "Branded Amarok still",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "branding-amarok-02",
    type: "image",
    src: "/media/fdl/branding/amarok-02.jpg",
    brand: "branding",
    brandLabel: "Branding",
    project: "amarok-europa",
    projectLabel: "Amarok Europa Branding",
    title: "Branding detail still",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "vw-amarok-01",
    type: "image",
    src: "/media/fdl/vw/amarok-01.jpg",
    brand: "vw",
    brandLabel: "VW",
    project: "amarok-bodykit-blackout",
    projectLabel: "VW Amarok Bodykit Blackout",
    title: "VW Amarok workshop angle",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "vw-amarok-02",
    type: "image",
    src: "/media/fdl/vw/amarok-02.jpg",
    brand: "vw",
    brandLabel: "VW",
    project: "amarok-bodykit-blackout",
    projectLabel: "VW Amarok Bodykit Blackout",
    title: "VW Amarok side detail",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "audi-r8-quick-clips",
    type: "video",
    src: "/media/fdl/audi/r8-quick-clips.m4v",
    poster: "/media/fdl/audi/r8-03.jpg",
    brand: "audi",
    brandLabel: "Audi",
    project: "audi-r8",
    projectLabel: "Audi R8",
    title: "Audi R8 quick clips",
    relatedSlugs: ["audi-r8"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "bmw-x5-lci-bodykit-ppf",
    type: "video",
    src: "/media/fdl/bmw/x5-lci-bodykit-ppf.m4v",
    poster: "/media/fdl/bmw/x5-lci-01.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x5-lci",
    projectLabel: "BMW X5 LCI",
    title: "BMW X5 LCI bodykit + PPF",
    relatedSlugs: ["x5-g05-lci"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "bmw-x5-g05-facelift-blue",
    type: "video",
    src: "/media/fdl/bmw/x5-g05-facelift-blue.m4v",
    poster: "/media/fdl/bmw/x5-g05-facelift-blue-01.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x5-g05-facelift",
    projectLabel: "BMW X5 G05 Facelift",
    title: "BMW X5 G05 facelift reel",
    relatedSlugs: ["x5-g05"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "bmw-x5m-blue",
    type: "video",
    src: "/media/fdl/bmw/x5m-blue.m4v",
    poster: "/media/fdl/bmw/x5m-carbon-02.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x5m-f95-blue",
    projectLabel: "BMW X5M F95 Blue",
    title: "BMW X5M F95 blue reel",
    relatedSlugs: ["x5m", "x5m-lci"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "bmw-x7-lci-brooklyn",
    type: "video",
    src: "/media/fdl/bmw/x7-lci-brooklyn.m4v",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x7-lci",
    projectLabel: "BMW X7 LCI",
    title: "BMW X7 LCI Brooklyn reel",
    relatedSlugs: ["x7-g07", "x7-g07-lci"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "bmw-x7-lci-white",
    type: "video",
    src: "/media/fdl/bmw/x7-lci-white.m4v",
    brand: "bmw",
    brandLabel: "BMW",
    project: "x7-lci",
    projectLabel: "BMW X7 LCI",
    title: "BMW X7 LCI white reel",
    relatedSlugs: ["x7-g07", "x7-g07-lci"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "bmw-xm-bodykit",
    type: "video",
    src: "/media/fdl/bmw/xm-bodykit.m4v",
    brand: "bmw",
    brandLabel: "BMW",
    project: "xm-bodykit",
    projectLabel: "BMW XM Bodykit",
    title: "BMW XM bodykit reel",
    relatedSlugs: ["xm"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "bmw-420d-f32-zayn",
    type: "video",
    src: "/media/fdl/bmw/420d-f32-zayn.m4v",
    poster: "/media/fdl/bmw/420d-f32-zayn-01.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "420d-f32-zayn",
    projectLabel: "BMW 420D F32 Zayn",
    title: "BMW 420D F32 Zayn reel",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "bmw-m3-f80-wrap-bodykit",
    type: "video",
    src: "/media/fdl/bmw/m3-f80-wrap-bodykit.m4v",
    poster: "/media/fdl/bmw/m3-f80-01.jpg",
    brand: "bmw",
    brandLabel: "BMW",
    project: "m3-f80",
    projectLabel: "BMW M3 F80",
    title: "BMW M3 F80 wrap + bodykit reel",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "bmw-g20-3-series-white",
    type: "video",
    src: "/media/fdl/bmw/g20-3-series-white.m4v",
    brand: "bmw",
    brandLabel: "BMW",
    project: "g20-3-series",
    projectLabel: "BMW G20 3 Series",
    title: "BMW G20 3 Series white reel",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "bmw-m5-touring",
    type: "video",
    src: "/media/fdl/bmw/m5-touring.m4v",
    brand: "bmw",
    brandLabel: "BMW",
    project: "m5-touring",
    projectLabel: "BMW M5 Touring",
    title: "BMW M5 Touring reel",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "defender-side-storage-box",
    type: "video",
    src: "/media/fdl/defender/side-storage-box.mp4",
    poster: "/media/fdl/defender/black-110-02.jpg",
    brand: "defender",
    brandLabel: "Defender",
    project: "product-upgrades",
    projectLabel: "Defender Product Upgrades",
    title: "Defender side storage box",
    relatedSlugs: ["land-rover-defender", "defender-l663"],
    featuredArea: ["defender", "gallery", "shop-category"],
  },
  {
    id: "defender-side-steps",
    type: "video",
    src: "/media/fdl/defender/side-steps.mp4",
    poster: "/media/fdl/defender/lm-satin-01.jpg",
    brand: "defender",
    brandLabel: "Defender",
    project: "product-upgrades",
    projectLabel: "Defender Product Upgrades",
    title: "Defender side steps",
    relatedSlugs: ["land-rover-defender", "defender-l663"],
    featuredArea: ["defender", "gallery", "shop-category"],
  },
  {
    id: "defender-led-strip-grill-light",
    type: "video",
    src: "/media/fdl/defender/led-strip-grill-light.mp4",
    poster: "/media/fdl/defender/v8-black-02.jpg",
    brand: "defender",
    brandLabel: "Defender",
    project: "product-upgrades",
    projectLabel: "Defender Product Upgrades",
    title: "Defender LED grill light",
    relatedSlugs: ["land-rover-defender", "defender-l663"],
    featuredArea: ["defender", "gallery", "shop-category"],
  },
  {
    id: "range-rover-sport-bodykit-black",
    type: "video",
    src: "/media/fdl/range-rover/sport-bodykit-black.m4v",
    poster: "/media/fdl/range-rover/sport-satin-02.jpg",
    brand: "range-rover",
    brandLabel: "Range Rover",
    project: "sport-lm-bodykit",
    projectLabel: "Range Rover Sport LM Bodykit",
    title: "Range Rover Sport bodykit drive",
    relatedSlugs: ["range-rover-sport", "l494-sport", "l461-sport"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "porsche-taycan-wrap-wheels",
    type: "video",
    src: "/media/fdl/porsche/taycan-wrap-wheels.m4v",
    poster: "/media/fdl/porsche/taycan-01.jpg",
    brand: "porsche",
    brandLabel: "Porsche",
    project: "taycan-wrap-wheels",
    projectLabel: "Porsche Taycan Wrap + Wheels",
    title: "Porsche Taycan wrap + wheels",
    relatedSlugs: ["taycan"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "mercedes-brabus-g63-carbon",
    type: "video",
    src: "/media/fdl/mercedes/brabus-g63-carbon.m4v",
    poster: "/media/fdl/mercedes/gle-01.jpg",
    brand: "mercedes",
    brandLabel: "Mercedes",
    project: "brabus-g63-carbon",
    projectLabel: "Brabus G63 Carbon",
    title: "Brabus G63 carbon package",
    relatedSlugs: ["g-wagon-g63"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "branding-amarok-europa",
    type: "video",
    src: "/media/fdl/branding/amarok-europa.m4v",
    poster: "/media/fdl/branding/amarok-01.jpg",
    brand: "branding",
    brandLabel: "Branding",
    project: "amarok-europa",
    projectLabel: "Amarok Europa Branding",
    title: "Amarok Europa branding reel",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "ford-ranger-bodykit-wheels",
    type: "video",
    src: "/media/fdl/ford/ranger-bodykit-wheels.m4v",
    poster: "/media/fdl/branding/amarok-02.jpg",
    brand: "ford",
    brandLabel: "Ford",
    project: "ranger-bodykit-wheels",
    projectLabel: "Ford Ranger Bodykit + Wheels",
    title: "Ford Ranger bodykit + wheels",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
  {
    id: "lamborghini-huracan-drive",
    type: "video",
    src: "/media/fdl/lamborghini/huracan-drive.m4v",
    poster: "/media/fdl/porsche/taycan-02.jpg",
    brand: "lamborghini",
    brandLabel: "Lamborghini",
    project: "huracan-drive",
    projectLabel: "Lamborghini Huracan Drive",
    title: "Lamborghini Huracan drive reel",
    relatedSlugs: ["huracan"],
    featuredArea: ["gallery", "shop-category"],
  },
  {
    id: "tesla-model-s-satin-blue",
    type: "video",
    src: "/media/fdl/tesla/model-s-satin-blue.m4v",
    poster: "/media/fdl/branding/amarok-01.jpg",
    brand: "tesla",
    brandLabel: "Tesla",
    project: "model-s-satin-blue",
    projectLabel: "Tesla Model S Satin Blue",
    title: "Tesla Model S satin blue wrap",
    relatedSlugs: [],
    featuredArea: ["gallery"],
  },
];

function findMediaById(id: string): CuratedMediaItem {
  const item = CURATED_MEDIA_ITEMS.find((entry) => entry.id === id);
  if (!item) {
    throw new Error(`Unknown curated media id: ${id}`);
  }
  return item;
}

function getMediaItemsByIds(ids: string[]): CuratedMediaItem[] {
  return ids.map((id) => findMediaById(id));
}

export const CURATED_MEDIA = CURATED_MEDIA_ITEMS;

export const HOME_HERO_MEDIA = [
  findMediaById("defender-black-110-01"),
  findMediaById("bmw-x5-lci-01"),
  findMediaById("audi-r8-03"),
  findMediaById("range-rover-sport-lm-01"),
];

export const HOME_EXPERTISE_MEDIA = findMediaById("defender-black-110-01");
export const DEFENDER_HERO_IMAGE = findMediaById("defender-black-110-01");
export const DEFENDER_GALLERY_MEDIA = [
  findMediaById("defender-black-110-02"),
  findMediaById("defender-lm-satin-01"),
  findMediaById("defender-v8-black-02"),
  findMediaById("defender-borasco-grey-01"),
  findMediaById("defender-lm-satin-02"),
];
export const DEFENDER_VIDEO_MEDIA = [
  findMediaById("defender-side-storage-box"),
  findMediaById("defender-side-steps"),
  findMediaById("defender-led-strip-grill-light"),
];

export const SERVICE_MEDIA: Record<string, CuratedMediaItem> = {
  bodykits: findMediaById("defender-black-110-01"),
  "alloy-refurb": findMediaById("bmw-x5-lci-02"),
  "privacy-glass": findMediaById("mercedes-gle-01"),
  "light-tinting": findMediaById("defender-v8-black-01"),
  wrapping: findMediaById("porsche-taycan-01"),
  "detailing-ppf": findMediaById("audi-r8-02"),
  security: findMediaById("mercedes-gle-02"),
  "accident-repair": findMediaById("range-rover-sport-lm-01"),
  "alloy-packages": findMediaById("range-rover-sport-satin-02"),
};

export const GALLERY_FILTER_LABELS: Record<string, string> = {
  all: "All",
  defender: "Defender",
  bmw: "BMW",
  audi: "Audi",
  "range-rover": "Range Rover",
  mercedes: "Mercedes",
  porsche: "Porsche",
  lamborghini: "Lamborghini",
  branding: "Branding",
  videos: "Videos",
  ford: "Ford",
  tesla: "Tesla",
  vw: "VW",
};

const FILTER_ORDER = [
  "all",
  "defender",
  "bmw",
  "audi",
  "range-rover",
  "mercedes",
  "porsche",
  "lamborghini",
  "branding",
  "videos",
  "ford",
  "tesla",
  "vw",
];

export const GALLERY_FILTERS = FILTER_ORDER.filter((key) => {
  if (key === "all" || key === "videos") return true;
  return CURATED_MEDIA_ITEMS.some((item) => item.brand === key);
}).map((key) => ({ key, label: GALLERY_FILTER_LABELS[key] || key }));

const SHOP_CATEGORY_MEDIA_MAP: Record<string, string[]> = {
  "audi-r8": ["audi-r8-01", "audi-r8-02", "audi-r8-03", "audi-r8-quick-clips"],
  "bmw-x5": ["bmw-x5-lci-01", "bmw-x5-lci-02", "bmw-x5-g05-facelift-blue-01", "bmw-x5-lci-bodykit-ppf"],
  "x5-g05-lci": ["bmw-x5-lci-01", "bmw-x5-lci-02", "bmw-x5-lci-03", "bmw-x5-lci-bodykit-ppf"],
  "x5-g05": ["bmw-x5-g05-facelift-blue-01", "bmw-x5-g05-facelift-white-01", "bmw-x5-g05-facelift-blue"],
  x5m: ["bmw-x5m-carbon-01", "bmw-x5m-carbon-02", "bmw-x5m-blue"],
  "x5m-lci": ["bmw-x5m-carbon-01", "bmw-x5m-carbon-02", "bmw-x5m-blue"],
  "x7-g07": ["bmw-x7-lci-brooklyn", "bmw-x7-lci-white"],
  "x7-g07-lci": ["bmw-x7-lci-brooklyn", "bmw-x7-lci-white"],
  xm: ["bmw-xm-bodykit"],
  "range-rover-sport": ["range-rover-sport-lm-01", "range-rover-sport-satin-01", "range-rover-sport-satin-02", "range-rover-sport-bodykit-black"],
  "l494-sport": ["range-rover-sport-lm-01", "range-rover-sport-satin-01", "range-rover-sport-satin-02", "range-rover-sport-bodykit-black"],
  "l461-sport": ["range-rover-sport-lm-01", "range-rover-sport-satin-01", "range-rover-sport-satin-02", "range-rover-sport-bodykit-black"],
  "land-rover-defender": ["defender-black-110-01", "defender-black-110-02", "defender-lm-satin-01", "defender-side-storage-box"],
  "defender-l663": ["defender-black-110-01", "defender-v8-black-01", "defender-lm-satin-02", "defender-led-strip-grill-light"],
  "g-wagon-g63": ["mercedes-brabus-g63-carbon"],
  gle: ["mercedes-gle-01", "mercedes-gle-02"],
  taycan: ["porsche-taycan-01", "porsche-taycan-02", "porsche-taycan-wrap-wheels"],
  huracan: ["lamborghini-huracan-drive"],
};

export function getGalleryItemsForFilter(filter: string): CuratedMediaItem[] {
  if (filter === "all") return CURATED_MEDIA_ITEMS;
  if (filter === "videos") return CURATED_MEDIA_ITEMS.filter((item) => item.type === "video");
  return CURATED_MEDIA_ITEMS.filter((item) => item.brand === filter);
}

export function getGalleryBrands(): string[] {
  return FILTER_ORDER.filter(
    (key) => key !== "all" && key !== "videos" && CURATED_MEDIA_ITEMS.some((item) => item.brand === key),
  );
}

export function getShopCategoryMedia(slug: string): CuratedMediaItem[] {
  const itemIds = SHOP_CATEGORY_MEDIA_MAP[slug];
  if (!itemIds) return [];
  return getMediaItemsByIds(itemIds);
}
